/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFramePackage;

import MainPackage.UniSync;
import static MainPackage.UniSync.calcGPA;
import static MainPackage.UniSync.result;
import static MainPackage.UniSync.stmt;
import static MainPackage.UniSync.student;
import java.awt.event.ItemEvent;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebte
 */
public class GradesPage extends javax.swing.JFrame {

    DefaultTableModel model;
    DecimalFormat decimalFormat = new DecimalFormat("#.##");
    /**
     * Creates new form MainPage
     */
    public GradesPage() {
        
        initComponents();
        
        //Load Courses table
        model = (DefaultTableModel) rSTableMetro2.getModel();
        try {
		UniSync.result= UniSync.stmt.executeQuery("Select * from courses inner join studentcourses using (Code) where Status=1 and StudentID = " + UniSync.getStudent().getStudentID());
			
		while (UniSync.result.next()) {
                    
                    model.insertRow(model.getRowCount(), new Object[] {UniSync.result.getString("Code"), UniSync.result.getDouble("Credits"), Double.parseDouble(decimalFormat.format(UniSync.result.getDouble("Grade"))), UniSync.result.getDouble("CourseAverage")});
					
                }			
	}catch(Exception e){
		e.printStackTrace();
	}
        
        
        
        //Load Combo Box options
        DefaultComboBoxModel modelCombo = (DefaultComboBoxModel) rSComboMetro1.getModel();
        try{
            UniSync.result = UniSync.stmt.executeQuery("Select * from courses inner join studentcourses using (Code) where Status=1 and StudentID =" + UniSync.getStudent().getStudentID() );
               
            while (UniSync.result.next()) {
                modelCombo.addElement(UniSync.result.getString("Code"));
            }
        }catch(Exception e){
            e.printStackTrace();
	}
        
        
        Double courseAvg = UniSync.calculateCourseGrade((String)modelCombo.getSelectedItem());
        jLabel4.setText("Current Grade in "+ (String)modelCombo.getSelectedItem());
        
        courseAvg = Double.parseDouble(decimalFormat.format(courseAvg));
        courseGradeLabel.setText(Double.toString(courseAvg)+ "%");
        
        double gpa = UniSync.calcGPA();
        gpa = Double.parseDouble(decimalFormat.format(gpa));
        gpaLabel.setText(Double.toString(gpa));
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_enterCourse = new app.bolivia.swing.JCTextField();
        addCourseButton = new rojerusan.RSMaterialButtonRectangle();
        deleteCourseButton = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro2 = new rojeru_san.complementos.RSTableMetro();
        errorMsg = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        courseGradeLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        gpaLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliverablesTable = new rojeru_san.complementos.RSTableMetro();
        txt_enterGrade = new app.bolivia.swing.JCTextField();
        modifyGradeButton = new rojerusan.RSMaterialButtonRectangle();
        txt_enterDelivNum = new app.bolivia.swing.JCTextField();
        errorMsg2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        setPreferredSize(new java.awt.Dimension(1200, 828));
        setSize(new java.awt.Dimension(1200, 828));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(204, 0, 51));
        rSMaterialButtonRectangle1.setText("Done");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("Enter Or Modify Your Courses Here");

        txt_enterCourse.setPlaceholder("Enter Course... (e.g APSC100)");
        txt_enterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enterCourseActionPerformed(evt);
            }
        });

        addCourseButton.setBackground(new java.awt.Color(204, 0, 51));
        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        deleteCourseButton.setBackground(new java.awt.Color(204, 0, 51));
        deleteCourseButton.setText("Delete Course");
        deleteCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseButtonActionPerformed(evt);
            }
        });

        rSTableMetro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Courses", "Credits", "Grade", "Average"
            }
        ));
        rSTableMetro2.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        jScrollPane2.setViewportView(rSTableMetro2);

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Grade");

        courseGradeLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        courseGradeLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseGradeLabel.setText("jLabel5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(courseGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(courseGradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 0, 51));

        gpaLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        gpaLabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Current GPA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(gpaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_enterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(errorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_enterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Modify Your Deliverables Here");

        rSComboMetro1.setToolTipText("");
        rSComboMetro1.setColorArrow(new java.awt.Color(204, 0, 51));
        rSComboMetro1.setColorBorde(new java.awt.Color(204, 0, 51));
        rSComboMetro1.setColorFondo(new java.awt.Color(204, 0, 51));
        rSComboMetro1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rSComboMetro1ItemStateChanged(evt);
            }
        });
        rSComboMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboMetro1ActionPerformed(evt);
            }
        });

        deliverablesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Grade", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deliverablesTable.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        jScrollPane1.setViewportView(deliverablesTable);

        txt_enterGrade.setPlaceholder("Enter Grade Obtained...");
        txt_enterGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enterGradeActionPerformed(evt);
            }
        });

        modifyGradeButton.setBackground(new java.awt.Color(204, 0, 51));
        modifyGradeButton.setText("Modify Grade");
        modifyGradeButton.setActionCommand("");
        modifyGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyGradeButtonActionPerformed(evt);
            }
        });

        txt_enterDelivNum.setPlaceholder("Enter Deliverable Number");
        txt_enterDelivNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enterDelivNumActionPerformed(evt);
            }
        });

        jLabel5.setText("Grade Calculator");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txt_enterDelivNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_enterGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorMsg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_enterGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyGradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_enterDelivNum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grades");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(504, 504, 504))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
       HomePage frame = new HomePage();
       frame.setVisible(true);
       dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void deleteCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseButtonActionPerformed
        String codeEntered = txt_enterCourse.getText();
        try{
            int res = UniSync.deleteCourses(UniSync.getStudent().getStudentID(), codeEntered);
        
            if (res == 1){
            DefaultComboBoxModel modelCombo = (DefaultComboBoxModel) rSComboMetro1.getModel();    
            DefaultTableModel model = (DefaultTableModel) rSTableMetro2.getModel();
            int rowCount = model.getRowCount();
            
            for (int row = 0; row < rowCount; row++) {
                Object name = rSTableMetro2.getValueAt(row, 0);
                if (name.equals(codeEntered)) {
                    model.removeRow(row);
                    modelCombo.removeElement(codeEntered);
                    break;
            }
        }
                
            errorMsg.setText("Course succesfully deleted");
            }else {
                errorMsg.setText("You're not enrolled in this course");
            }
        }catch(Exception e){
            e.printStackTrace();
	}
    }//GEN-LAST:event_deleteCourseButtonActionPerformed

    private void txt_enterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enterCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enterCourseActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        String codeEntered = txt_enterCourse.getText();
        try{
            DefaultTableModel model = (DefaultTableModel) rSTableMetro2.getModel();
            DefaultComboBoxModel modelCombo = (DefaultComboBoxModel) rSComboMetro1.getModel();
            
            int res = UniSync.addCourses(UniSync.getStudent().getStudentID(), codeEntered);
        
            switch (res) {
                case 1:
                    errorMsg.setText("Course has already been added");
                    break;
                case 2:
                    UniSync.result = UniSync.stmt.executeQuery("Select * from courses inner join studentcourses using (Code) where Status=1 and StudentID =" + UniSync.getStudent().getStudentID() );
                    while (UniSync.result.next()) {
                        if (UniSync.result.getString("Code").equals(codeEntered)){
                            model.addRow(new Object[] {UniSync.result.getString("Code"), UniSync.result.getDouble("Credits"), UniSync.result.getDouble("Grade"), UniSync.result.getDouble("CourseAverage") });
                            modelCombo.addElement(UniSync.result.getString("Code"));
                        }
                        
                    }   
                    errorMsg.setText("Course succesfully added");
                    double gpa = UniSync.calcGPA();
                    gpa = Double.parseDouble(decimalFormat.format(gpa));
                    gpaLabel.setText(Double.toString(gpa));
                    break;
                default:
                    errorMsg.setText("Course does not exist");
                    break;
            }
        }catch(Exception e){
            e.printStackTrace();
	}
        
        
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void txt_enterGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enterGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enterGradeActionPerformed

    private void modifyGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyGradeButtonActionPerformed
        DefaultTableModel modelDelivTable = (DefaultTableModel) deliverablesTable.getModel();
        DefaultTableModel modelCourseTable = (DefaultTableModel) rSTableMetro2.getModel();
        DefaultComboBoxModel modelCombo = (DefaultComboBoxModel) rSComboMetro1.getModel();
        
        String courseSelected = (String)modelCombo.getSelectedItem();
        int numEntered = Integer.parseInt(txt_enterDelivNum.getText());
        Double gradeEntered = Double.valueOf(txt_enterGrade.getText());
        
        
        try{
            
   
            int res = UniSync.updateGrade(numEntered, gradeEntered, courseSelected);
        
            switch (res) {
                case 1:
                    modelDelivTable.setValueAt(gradeEntered, numEntered-1, 2);
                    
                    Double courseAvg = UniSync.calculateCourseGrade(courseSelected);
                    
                    int rowCount = modelCourseTable.getRowCount();
            
                    for (int row = 0; row < rowCount; row++) {
                        Object course = rSTableMetro2.getValueAt(row, 0);
                        if (course.equals(courseSelected)) {
                            modelCourseTable.setValueAt(courseAvg, row, 2);
                            break;
                        }    
                    }
                    jLabel4.setText("Current Grade in "+ courseSelected);
                    courseAvg = Double.parseDouble(decimalFormat.format(courseAvg));
                  
                    courseGradeLabel.setText(Double.toString(courseAvg)+ "%");
                    
                    double gpa = UniSync.calcGPA();
                    gpa = Double.parseDouble(decimalFormat.format(gpa));
                    gpaLabel.setText(Double.toString(gpa));
                    break;
                
                default:
                    errorMsg2.setText("Deliverable does not exist");
                    break;
            }
        }catch(Exception e){
            e.printStackTrace();
	}
    }//GEN-LAST:event_modifyGradeButtonActionPerformed

    private void txt_enterDelivNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enterDelivNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enterDelivNumActionPerformed

    private void rSComboMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboMetro1ActionPerformed
        
    }//GEN-LAST:event_rSComboMetro1ActionPerformed
    private boolean isUpdating = false;
    private void rSComboMetro1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rSComboMetro1ItemStateChanged
        
        DefaultTableModel model = (DefaultTableModel) deliverablesTable.getModel();

        if (evt.getStateChange() == ItemEvent.SELECTED && !isUpdating) {
            isUpdating = true;

            JComboBox<String> source = (JComboBox<String>) evt.getSource();
            String selectedItem = (String) source.getSelectedItem();
            model.setRowCount(0);

            try {
                UniSync.result = UniSync.stmt.executeQuery("Select * from deliverables inner join studentdeliverables ON deliverables.Code = studentdeliverables.Code AND deliverables.DeliverableNum = studentdeliverables.DeliverableNum where studentdeliverables.StudentID =" + UniSync.getStudent().getStudentID());

                while (UniSync.result.next()) {
                    if (UniSync.result.getString("Code").equals(selectedItem)) {
                        model.addRow(new Object[] { UniSync.result.getInt("DeliverableNum"), UniSync.result.getString("DeliverableName"), UniSync.result.getDouble("DeliverableGrade"), UniSync.result.getDouble("DeliverableWeight") });
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            DefaultComboBoxModel modelCombo = (DefaultComboBoxModel) rSComboMetro1.getModel();
            try {
                modelCombo.removeAllElements();

                UniSync.result = UniSync.stmt.executeQuery("Select * from courses inner join studentcourses using (Code) where Status=1 and StudentID =" + UniSync.getStudent().getStudentID());

                while (UniSync.result.next()) {
                    modelCombo.addElement(UniSync.result.getString("Code"));
                }
                modelCombo.setSelectedItem(selectedItem);
            } catch (Exception e) {
                e.printStackTrace();
            }

            isUpdating = false;
            
            
            
            Double courseAvg = UniSync.calculateCourseGrade((String)modelCombo.getSelectedItem());
            jLabel4.setText("Current Grade in "+ (String)modelCombo.getSelectedItem());
            courseAvg = Double.parseDouble(decimalFormat.format(courseAvg));
            courseGradeLabel.setText(Double.toString(courseAvg)+ "%");
        }
            
    }//GEN-LAST:event_rSComboMetro1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle addCourseButton;
    private javax.swing.JLabel courseGradeLabel;
    private rojerusan.RSMaterialButtonRectangle deleteCourseButton;
    private rojeru_san.complementos.RSTableMetro deliverablesTable;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel errorMsg2;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonRectangle modifyGradeButton;
    private rojerusan.RSComboMetro rSComboMetro1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro2;
    private app.bolivia.swing.JCTextField txt_enterCourse;
    private app.bolivia.swing.JCTextField txt_enterDelivNum;
    private app.bolivia.swing.JCTextField txt_enterGrade;
    // End of variables declaration//GEN-END:variables
}
